plugins {
    id 'java'
}

group = 'nl.hollandsmp'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        url = uri('https://repo.lax1dude.net/repository/releases/')
    }
    maven {
        name = 'spigot-repo'
        url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/')
    }
}

dependencies {
    compileOnly files('libs/spigot-stub.jar') // local lightweight stubs for compilation only
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:unchecked', '-Xlint:deprecation']
}

jar {
    archiveBaseName = 'LingeringDragonBreathFix'
    // Do not include compileOnly dependencies in the plugin JAR. They are provided by the server.
}
